# Generated by Django 4.1.3 on 2022-11-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_artcile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='Категории'),
        ),
    ]
