# Generated by Django 4.1.3 on 2022-11-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artcile',
            new_name='Article',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_article',
            field=models.ManyToManyField(to='blog.article'),
        ),
    ]
