# Generated by Django 4.1.3 on 2022-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_artcile_article_tag_tag_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_article',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Хэштеги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Хештег'),
        ),
    ]
