# Generated by Django 4.1.3 on 2022-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_tag_tag_article_article_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tег', 'verbose_name_plural': 'Tеги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(blank=True, to='blog.article', verbose_name='Статьи с такими тегами'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tеги'),
        ),
    ]
