# Generated by Django 4.1.3 on 2023-02-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.TextField(blank=True, verbose_name='Автор'),
        ),
    ]
